// Zi Wei Dou Shu — Dual Star Combinations (双星同宫)

export interface ZiweiCombination {
  slug: string;
  star1_en: string;
  star1_zh: string;
  star2_en: string;
  star2_zh: string;
  nature_en: string;
  nature_zh: string;
  description_en: string;
  description_zh: string;
  strengths_en: string[];
  strengths_zh: string[];
  challenges_en: string[];
  challenges_zh: string[];
  palace_effects_en: string;
  palace_effects_zh: string;
}

export const ZIWEI_COMBINATIONS: ZiweiCombination[] = [
  {
    slug: "ziwei-tianfu",
    star1_en: "Zi Wei (Emperor)",
    star1_zh: "紫微",
    star2_en: "Tian Fu (Treasury)",
    star2_zh: "天府",
    nature_en: "Supreme Authority + Steady Wealth",
    nature_zh: "至尊权威 + 稳健财富",
    description_en: "When Zi Wei and Tian Fu share a palace, it combines the emperor's authority with the treasurer's stability. This is one of the most auspicious dual-star configurations, indicating someone who possesses both leadership charisma and financial prudence. The person naturally attracts resources while maintaining dignified composure.",
    description_zh: "紫微天府同宫，结合了帝王的权威与库府的稳重。这是最吉利的双星组合之一，意味着此人既有领导魅力又有理财头脑。自然吸引资源，同时保持尊贵的风度。",
    strengths_en: ["Natural leadership combined with financial wisdom", "Commands respect without being aggressive", "Excellent at building and preserving wealth", "Stable temperament with high ambition"],
    strengths_zh: ["领导力与理财智慧兼具", "不怒自威，令人敬服", "善于积累和守护财富", "性情稳重且志向远大"],
    challenges_en: ["May appear overly conservative or rigid", "Can be too focused on status and material security", "Risk of complacency due to ease of success"],
    challenges_zh: ["可能显得过于保守或固执", "过度关注地位和物质安全", "因成功来得容易而有自满风险"],
    palace_effects_en: "In the Life Palace: natural born leader with wealth magnetism. In Career Palace: executive success in finance or government. In Wealth Palace: steady accumulation, rarely faces poverty.",
    palace_effects_zh: "在命宫：天生领袖具有聚财体质。在官禄宫：适合金融或政府的高管职位。在财帛宫：稳健积累，鲜少贫困。",
  },
  {
    slug: "ziwei-tanlang",
    star1_en: "Zi Wei (Emperor)",
    star1_zh: "紫微",
    star2_en: "Tan Lang (Greedy Wolf)",
    star2_zh: "贪狼",
    nature_en: "Noble Authority + Desire & Charm",
    nature_zh: "尊贵权威 + 欲望魅力",
    description_en: "Zi Wei with Tan Lang creates a fascinating blend of royal dignity and earthy desire. The emperor meets the entertainer — resulting in someone who is both commanding and charismatic, with strong social skills and artistic sensibilities. This person knows how to enjoy life while maintaining authority.",
    description_zh: "紫微贪狼同宫，创造了皇家尊严与世俗欲望的奇妙融合。帝王遇上才子——既有号令天下的气势，又有社交魅力和艺术天赋。此人懂得享受生活同时不失权威。",
    strengths_en: ["Exceptional social charisma and networking ability", "Creative leadership style", "Ability to turn pleasure into profit", "Magnetic personality that draws followers"],
    strengths_zh: ["卓越的社交魅力和人脉能力", "创造性的领导风格", "能将兴趣转化为事业", "磁性人格吸引追随者"],
    challenges_en: ["Tendency toward indulgence and scattered focus", "May struggle between duty and desire", "Risk of romantic complications in positions of power"],
    challenges_zh: ["有放纵和分散精力的倾向", "在责任与欲望间挣扎", "在权力地位上有感情纠纷风险"],
    palace_effects_en: "In Life Palace: charismatic leader with artistic talent. In Spouse Palace: passionate but complex relationships. In Career Palace: success in entertainment, hospitality, or creative industries.",
    palace_effects_zh: "在命宫：有艺术才华的魅力型领袖。在夫妻宫：热烈但复杂的感情。在官禄宫：适合娱乐、餐饮或创意产业。",
  },
  {
    slug: "ziwei-qisha",
    star1_en: "Zi Wei (Emperor)",
    star1_zh: "紫微",
    star2_en: "Qi Sha (Seven Kills)",
    star2_zh: "七杀",
    nature_en: "Supreme Command + Warrior Spirit",
    nature_zh: "至尊统帅 + 将帅之才",
    description_en: "Zi Wei with Qi Sha is the emperor who leads from the front lines. This powerful combination produces decisive, action-oriented leaders who are unafraid of challenges. They have both strategic vision and tactical courage, making them formidable in competitive environments.",
    description_zh: "紫微七杀同宫，是御驾亲征的帝王。这一强力组合产生果断、行动导向的领袖，不惧挑战。既有战略眼光又有战术勇气，在竞争环境中令人生畏。",
    strengths_en: ["Decisive leadership in crisis situations", "Combines strategic thinking with bold action", "Natural authority that inspires courage in others", "Thrives under pressure and competition"],
    strengths_zh: ["危机中果断的领导力", "战略思维与大胆行动兼备", "天然威信激发他人勇气", "在压力和竞争中茁壮成长"],
    challenges_en: ["Can be overly domineering or intimidating", "May make enemies through aggressive ambition", "Difficulty delegating or trusting subordinates"],
    challenges_zh: ["可能过于强势或令人畏惧", "激进的野心可能树敌", "难以授权或信任下属"],
    palace_effects_en: "In Life Palace: born commander, military or corporate warrior. In Career Palace: rapid rise through bold decisions. In Migration Palace: success far from hometown, overseas leadership.",
    palace_effects_zh: "在命宫：天生统帅，军事或企业战将。在官禄宫：凭大胆决策快速晋升。在迁移宫：远离故土发展成功。",
  },
  {
    slug: "ziwei-pojun",
    star1_en: "Zi Wei (Emperor)",
    star1_zh: "紫微",
    star2_en: "Po Jun (Breaker)",
    star2_zh: "破军",
    nature_en: "Royal Authority + Revolutionary Change",
    nature_zh: "皇权 + 革新破立",
    description_en: "Zi Wei with Po Jun creates the reformist ruler — someone with the authority to tear down old systems and build new ones. This combination produces visionaries who are not content with the status quo, using their position to drive transformation.",
    description_zh: "紫微破军同宫，造就了改革型的统治者——有权力推翻旧体制、建立新秩序。这一组合产生不满现状的远见者，利用地位推动变革。",
    strengths_en: ["Visionary leadership that drives transformation", "Courage to challenge established systems", "Ability to rebuild after destruction", "Pioneer spirit with authority to execute"],
    strengths_zh: ["驱动变革的远见卓识", "挑战既有体制的勇气", "破后重建的能力", "有权力执行的开拓精神"],
    challenges_en: ["May destroy before having a clear plan to rebuild", "Relationships can suffer from constant upheaval", "Others may find the pace of change exhausting"],
    challenges_zh: ["可能在没有明确重建计划前就破坏", "不断变动可能伤害人际关系", "他人可能觉得变化节奏太快"],
    palace_effects_en: "In Life Palace: transformative leader, startup founder type. In Wealth Palace: volatile finances, big wins and losses. In Career Palace: disruptive innovator in their field.",
    palace_effects_zh: "在命宫：变革型领导，创业者类型。在财帛宫：财务波动大，大起大落。在官禄宫：所在领域的颠覆式创新者。",
  },
  {
    slug: "ziwei-tianxiang",
    star1_en: "Zi Wei (Emperor)",
    star1_zh: "紫微",
    star2_en: "Tian Xiang (Seal)",
    star2_zh: "天相",
    nature_en: "Authority + Diplomatic Grace",
    nature_zh: "权威 + 外交风度",
    description_en: "Zi Wei with Tian Xiang blends authority with diplomacy. The emperor has a skilled prime minister at hand — this produces leaders who govern through harmony rather than force. They excel at building consensus and maintaining institutional order.",
    description_zh: "紫微天相同宫，权威与外交并重。帝王身边有能干的宰相——产生以和谐而非武力治理的领袖。善于建立共识和维护制度秩序。",
    strengths_en: ["Leadership through consensus and diplomacy", "Excellent institutional management", "Trusted by both superiors and subordinates", "Balances authority with approachability"],
    strengths_zh: ["以共识和外交实现领导", "卓越的制度管理能力", "上下皆信任", "权威与亲和力兼备"],
    challenges_en: ["May be too people-pleasing to make tough decisions", "Can become overly bureaucratic", "Risk of being manipulated by strong advisors"],
    challenges_zh: ["可能因顾及人情而难做决断", "可能变得过于官僚", "有被强势幕僚操控的风险"],
    palace_effects_en: "In Life Palace: diplomatic leader, natural mediator. In Career Palace: success in government, HR, or law. In Friends Palace: surrounded by helpful allies.",
    palace_effects_zh: "在命宫：外交型领袖，天生调解者。在官禄宫：适合政府、人事或法律行业。在仆役宫：身边贵人多助。",
  },
  {
    slug: "tianji-taiyin",
    star1_en: "Tian Ji (Heavenly Secret)",
    star1_zh: "天机",
    star2_en: "Tai Yin (Moon)",
    star2_zh: "太阴",
    nature_en: "Intelligence + Intuition",
    nature_zh: "智慧 + 直觉",
    description_en: "Tian Ji with Tai Yin combines analytical intelligence with lunar intuition. This creates deeply perceptive individuals who understand both logic and emotion. They excel in fields requiring both calculation and sensitivity.",
    description_zh: "天机太阴同宫，分析智慧与月亮直觉结合。造就深具洞察力的人，兼通逻辑与情感。在需要计算和敏感度的领域出类拔萃。",
    strengths_en: ["Exceptional intuition backed by analytical thinking", "Creative problem-solving ability", "Deep emotional intelligence", "Talent for arts, research, and counseling"],
    strengths_zh: ["分析思维支撑的超群直觉", "创造性解决问题的能力", "深厚的情商", "艺术、研究和咨询的天赋"],
    challenges_en: ["Overthinking and indecisiveness", "Emotional sensitivity leading to mood swings", "May appear cold or detached while processing internally"],
    challenges_zh: ["过度思考和优柔寡断", "情感敏感导致情绪起伏", "内心加工时可能显得冷漠"],
    palace_effects_en: "In Life Palace: intuitive intellectual, suited for research. In Wealth Palace: income through creativity and intellectual property. In Health Palace: watch for mental stress and sleep issues.",
    palace_effects_zh: "在命宫：直觉型知识分子，适合研究工作。在财帛宫：通过创意和知识产权获利。在疾厄宫：注意精神压力和睡眠问题。",
  },
  {
    slug: "tianji-jumen",
    star1_en: "Tian Ji (Heavenly Secret)",
    star1_zh: "天机",
    star2_en: "Ju Men (Giant Gate)",
    star2_zh: "巨门",
    nature_en: "Quick Mind + Eloquent Speech",
    nature_zh: "机敏 + 口才",
    description_en: "Tian Ji with Ju Men produces brilliant communicators — sharp minds paired with powerful expression. These individuals can analyze complex ideas and articulate them clearly. They excel in debate, teaching, media, and any field where words are weapons.",
    description_zh: "天机巨门同宫，产生出色的沟通者——敏锐的头脑配上强大的表达力。能分析复杂思想并清晰阐述。在辩论、教学、传媒等以言辞为利器的领域出类拔萃。",
    strengths_en: ["Brilliant argumentation and persuasion skills", "Quick-witted response in any situation", "Excellent teaching and explanation ability", "Analytical depth combined with communication power"],
    strengths_zh: ["出色的论证和说服技巧", "任何场合的快速机智反应", "优秀的教学和解释能力", "分析深度与沟通力量结合"],
    challenges_en: ["Sharp tongue can hurt relationships", "May come across as argumentative", "Tendency to overthink what others say"],
    challenges_zh: ["言辞锋利可能伤害关系", "可能给人好辩的印象", "倾向于过度解读他人话语"],
    palace_effects_en: "In Life Palace: natural debater, lawyer, or journalist. In Career Palace: success in media, law, education. In Spouse Palace: communication-heavy relationship dynamics.",
    palace_effects_zh: "在命宫：天生辩手、律师或记者。在官禄宫：适合传媒、法律、教育。在夫妻宫：关系中沟通密度高。",
  },
  {
    slug: "tianji-tianliang",
    star1_en: "Tian Ji (Heavenly Secret)",
    star1_zh: "天机",
    star2_en: "Tian Liang (Heavenly Beam)",
    star2_zh: "天梁",
    nature_en: "Strategy + Wisdom & Protection",
    nature_zh: "谋略 + 智慧荫蔽",
    description_en: "Tian Ji with Tian Liang pairs strategic thinking with elder wisdom. This combination produces sage advisors who can see through complexity and offer guidance. They are natural mentors and problem-solvers, often protecting others from harm through foresight.",
    description_zh: "天机天梁同宫，谋略与长者智慧搭配。产生能看透复杂局势并提供指导的智囊。天生的导师和问题解决者，常以远见保护他人免受伤害。",
    strengths_en: ["Wise counsel that others seek and trust", "Ability to turn crises into opportunities", "Natural protective instinct for loved ones", "Long-term strategic vision"],
    strengths_zh: ["他人寻求和信赖的明智建议", "化危机为转机的能力", "对亲人天然的保护本能", "长远的战略眼光"],
    challenges_en: ["May worry excessively about others", "Tendency to be overly cautious", "Can miss opportunities by over-analyzing"],
    challenges_zh: ["可能过度操心他人", "倾向过于谨慎", "过度分析可能错失良机"],
    palace_effects_en: "In Life Palace: natural advisor, strategist, or doctor. In Parents Palace: strong family protection. In Career Palace: success in consulting, medicine, or spiritual guidance.",
    palace_effects_zh: "在命宫：天生顾问、战略家或医生。在父母宫：家庭庇护力强。在官禄宫：适合咨询、医学或灵性指导。",
  },
  {
    slug: "taiyang-taiyin",
    star1_en: "Tai Yang (Sun)",
    star1_zh: "太阳",
    star2_en: "Tai Yin (Moon)",
    star2_zh: "太阴",
    nature_en: "Sun + Moon Harmony",
    nature_zh: "日月同辉",
    description_en: "Tai Yang with Tai Yin — Sun and Moon together — represents the ultimate yin-yang balance. This rare and poetic combination produces individuals who embody both masculine drive and feminine grace, outward generosity and inner richness.",
    description_zh: "太阳太阴同宫——日月同辉——代表终极的阴阳平衡。这一罕见而诗意的组合产生兼具阳刚进取与阴柔优雅、外在慷慨与内在丰富的人。",
    strengths_en: ["Perfect balance of active and receptive energies", "Generous publicly while nurturing privately", "Adaptable to any social situation", "Success in both career and family"],
    strengths_zh: ["主动与接纳能量的完美平衡", "公开慷慨同时私下呵护", "适应任何社交场合", "事业与家庭双丰收"],
    challenges_en: ["Internal conflict between outgoing and introverted sides", "May overextend trying to please everyone", "Brightness depends heavily on palace position"],
    challenges_zh: ["外向与内向面之间的内在冲突", "可能因讨好所有人而透支", "光亮度严重依赖宫位"],
    palace_effects_en: "In Life Palace: balanced personality, respected by all. In Wealth Palace: income from both active work and passive investments. In Spouse Palace: harmonious partnership if both stars are bright.",
    palace_effects_zh: "在命宫：性格平衡，受众人尊敬。在财帛宫：主动劳动与被动投资皆有收入。在夫妻宫：若双星明亮则伴侣和谐。",
  },
  {
    slug: "taiyang-jumen",
    star1_en: "Tai Yang (Sun)",
    star1_zh: "太阳",
    star2_en: "Ju Men (Giant Gate)",
    star2_zh: "巨门",
    nature_en: "Radiance + Verbal Power",
    nature_zh: "光明 + 口才力量",
    description_en: "Tai Yang with Ju Men combines solar radiance with eloquent expression. The Sun illuminates what Ju Men speaks — producing charismatic public speakers, broadcasters, and leaders whose words carry weight and warmth.",
    description_zh: "太阳巨门同宫，太阳的光芒照亮巨门的言辞。产生有魅力的公众演说家、主播和领袖，其话语既有分量又有温度。",
    strengths_en: ["Powerful public speaking and broadcasting talent", "Words that inspire and illuminate", "Natural teacher who makes complex ideas accessible", "Charismatic presence in media"],
    strengths_zh: ["强大的公众演说和播音天赋", "言辞启发且照亮人心", "能将复杂概念变得通俗的天生教师", "在传媒中有魅力存在感"],
    challenges_en: ["May attract controversy through outspoken nature", "Ego can inflate with public attention", "The 'dark mouth' of Ju Men can turn criticism into public disputes"],
    challenges_zh: ["直言不讳可能招致争议", "公众关注可能膨胀自我", "巨门的'暗'面可能将批评变成公开纷争"],
    palace_effects_en: "In Life Palace: born broadcaster, teacher, or influencer. In Career Palace: success in media, politics, or education. In Migration Palace: fame in foreign lands.",
    palace_effects_zh: "在命宫：天生主播、教师或意见领袖。在官禄宫：适合传媒、政治或教育。在迁移宫：在外地扬名。",
  },
  {
    slug: "taiyang-tianliang",
    star1_en: "Tai Yang (Sun)",
    star1_zh: "太阳",
    star2_en: "Tian Liang (Heavenly Beam)",
    star2_zh: "天梁",
    nature_en: "Generosity + Protective Wisdom",
    nature_zh: "慷慨 + 荫蔽智慧",
    description_en: "Tai Yang with Tian Liang combines solar generosity with elder protection. Like a benevolent king with a wise minister, this produces philanthropic leaders who use their position to shelter and elevate others.",
    description_zh: "太阳天梁同宫，太阳的慷慨与天梁的荫蔽结合。如仁君配贤相，产生利用自身地位庇护和提拔他人的慈善型领袖。",
    strengths_en: ["Naturally protective of the weak and vulnerable", "Earned respect through genuine generosity", "Excellent in public service and charity", "Wise use of influence for collective good"],
    strengths_zh: ["天生保护弱者", "通过真诚慷慨赢得尊重", "在公共服务和慈善中出色", "明智地运用影响力服务集体"],
    challenges_en: ["May sacrifice personal interests for others excessively", "Can attract dependents who drain energy", "Tendency to take on too much responsibility"],
    challenges_zh: ["可能过度牺牲个人利益", "可能吸引消耗精力的依赖者", "倾向承担过多责任"],
    palace_effects_en: "In Life Palace: philanthropist, social worker, or respected elder. In Parents Palace: born into a family of status. In Career Palace: success in government, non-profits, or medicine.",
    palace_effects_zh: "在命宫：慈善家、社工或受人尊敬的长者。在父母宫：出身名门。在官禄宫：适合政府、公益或医疗。",
  },
  {
    slug: "wuqu-tianfu",
    star1_en: "Wu Qu (Military Music)",
    star1_zh: "武曲",
    star2_en: "Tian Fu (Treasury)",
    star2_zh: "天府",
    nature_en: "Financial Prowess + Wealth Preservation",
    nature_zh: "财星 + 守财库",
    description_en: "Wu Qu with Tian Fu is the ultimate wealth combination — the finance star meets the treasury. This produces exceptional financial managers, bankers, and investors who both generate and protect wealth with disciplined precision.",
    description_zh: "武曲天府同宫是终极财富组合——财星遇上金库。产生杰出的金融管理者、银行家和投资者，以严谨精确的方式生财和守财。",
    strengths_en: ["Supreme financial acumen and money management", "Disciplined approach to wealth building", "Trustworthy with other people's assets", "Conservative growth that compounds over time"],
    strengths_zh: ["顶级的金融头脑和资金管理能力", "有纪律的财富积累方式", "值得信赖的资产托管者", "随时间复利增长的保守策略"],
    challenges_en: ["May be overly focused on material wealth", "Can appear cold or calculating in relationships", "Difficulty enjoying money due to hoarding tendency"],
    challenges_zh: ["可能过于关注物质财富", "在关系中可能显得冷酷或精于算计", "因囤积倾向而难以享受财富"],
    palace_effects_en: "In Life Palace: born financier or wealth manager. In Wealth Palace: one of the best positions for accumulating riches. In Career Palace: success in banking, real estate, or investment.",
    palace_effects_zh: "在命宫：天生金融家。在财帛宫：最佳聚财位置之一。在官禄宫：适合银行、房地产或投资。",
  },
  {
    slug: "wuqu-tanlang",
    star1_en: "Wu Qu (Military Music)",
    star1_zh: "武曲",
    star2_en: "Tan Lang (Greedy Wolf)",
    star2_zh: "贪狼",
    nature_en: "Wealth + Desire & Versatility",
    nature_zh: "财星 + 欲望多才",
    description_en: "Wu Qu with Tan Lang blends financial sharpness with worldly desire. This produces entrepreneurs who pursue wealth through enjoyment — succeeding in hospitality, entertainment, or luxury industries where money and pleasure intersect.",
    description_zh: "武曲贪狼同宫，财务敏锐与世俗欲望融合。产生通过享乐追求财富的创业者——在餐饮、娱乐或奢侈品行业成功，金钱与快乐交汇。",
    strengths_en: ["Entrepreneurial talent in lifestyle industries", "Ability to monetize hobbies and pleasures", "Social networking that generates business", "Versatile skills across multiple domains"],
    strengths_zh: ["生活方式产业的创业天赋", "将兴趣爱好变现的能力", "产生商机的社交人脉", "跨领域的多才多艺"],
    challenges_en: ["Financial instability from impulsive spending", "Business mixed with pleasure can blur boundaries", "May pursue too many ventures simultaneously"],
    challenges_zh: ["冲动消费导致财务不稳", "生意与享乐混合可能模糊界限", "可能同时追求太多项目"],
    palace_effects_en: "In Life Palace: lifestyle entrepreneur. In Wealth Palace: income from entertainment or luxury. In Spouse Palace: partner may be extravagant.",
    palace_effects_zh: "在命宫：生活方式创业者。在财帛宫：从娱乐或奢侈品获利。在夫妻宫：伴侣可能爱好奢华。",
  },
  {
    slug: "wuqu-qisha",
    star1_en: "Wu Qu (Military Music)",
    star1_zh: "武曲",
    star2_en: "Qi Sha (Seven Kills)",
    star2_zh: "七杀",
    nature_en: "Financial Warrior + Decisive Action",
    nature_zh: "财帅 + 果断行动",
    description_en: "Wu Qu with Qi Sha creates the financial warrior — someone who pursues wealth with military precision and fearless determination. They are bold investors, aggressive traders, or tough-negotiating business leaders.",
    description_zh: "武曲七杀同宫创造了财务战士——以军事般的精准和无畏的决心追求财富。是大胆的投资者、激进的交易员或强硬谈判的商业领袖。",
    strengths_en: ["Fearless in financial risk-taking", "Decisive action in business negotiations", "Ability to thrive in competitive markets", "Strong execution power for wealth creation"],
    strengths_zh: ["金融冒险无所畏惧", "商业谈判中果断行动", "在竞争激烈的市场中茁壮成长", "强大的财富创造执行力"],
    challenges_en: ["High risk tolerance can lead to major losses", "May alienate allies through aggressive tactics", "Work-life balance is often sacrificed"],
    challenges_zh: ["高风险偏好可能导致重大损失", "激进策略可能疏远盟友", "工作生活平衡常被牺牲"],
    palace_effects_en: "In Life Palace: aggressive entrepreneur or trader. In Wealth Palace: volatile but potentially huge gains. In Career Palace: success through bold, risky ventures.",
    palace_effects_zh: "在命宫：激进的创业者或交易员。在财帛宫：波动大但可能有巨大收益。在官禄宫：通过大胆冒险获得成功。",
  },
  {
    slug: "wuqu-pojun",
    star1_en: "Wu Qu (Military Music)",
    star1_zh: "武曲",
    star2_en: "Po Jun (Breaker)",
    star2_zh: "破军",
    nature_en: "Wealth + Destruction & Rebuilding",
    nature_zh: "财星 + 破立再造",
    description_en: "Wu Qu with Po Jun combines financial energy with destructive-creative force. Money is earned, lost, and re-earned in dramatic cycles. These individuals often experience radical financial transformations throughout life.",
    description_zh: "武曲破军同宫，财务能量与破坏-创造力结合。金钱在戏剧性的循环中赚得、失去、再赚回。这些人一生中常经历激进的财务转变。",
    strengths_en: ["Ability to rebuild wealth from scratch", "Innovative approaches to making money", "Not afraid of financial failure", "Pioneer in new industries or markets"],
    strengths_zh: ["从零重建财富的能力", "赚钱的创新方法", "不惧财务失败", "新行业或市场的先锋"],
    challenges_en: ["Extreme financial volatility", "Difficulty maintaining stable savings", "May destroy profitable ventures out of restlessness"],
    challenges_zh: ["极端的财务波动", "难以维持稳定储蓄", "可能因不安分而毁掉盈利的事业"],
    palace_effects_en: "In Life Palace: serial entrepreneur with dramatic life changes. In Wealth Palace: boom-and-bust financial pattern. In Career Palace: frequent career pivots and industry changes.",
    palace_effects_zh: "在命宫：人生剧变的连续创业者。在财帛宫：大起大落的财务模式。在官禄宫：频繁的职业转型。",
  },
  {
    slug: "wuqu-tianxiang",
    star1_en: "Wu Qu (Military Music)",
    star1_zh: "武曲",
    star2_en: "Tian Xiang (Seal)",
    star2_zh: "天相",
    nature_en: "Financial Discipline + Institutional Support",
    nature_zh: "财务纪律 + 制度支持",
    description_en: "Wu Qu with Tian Xiang combines financial ability with institutional grace. These individuals succeed in structured financial environments — banking, accounting, government finance — where discipline and protocol lead to steady advancement.",
    description_zh: "武曲天相同宫，财务能力与制度优雅结合。这些人在结构化的金融环境中成功——银行、会计、政府财政——纪律和规范带来稳步晋升。",
    strengths_en: ["Thrives in institutional financial roles", "Trusted with authority over resources", "Diplomatic approach to financial management", "Steady career advancement through reliability"],
    strengths_zh: ["在机构金融职位中如鱼得水", "被信任管理资源", "外交式的财务管理方式", "以可靠性获得稳步晋升"],
    challenges_en: ["May lack entrepreneurial boldness", "Over-reliance on institutional structures", "Can be too conservative in investment decisions"],
    challenges_zh: ["可能缺乏创业的果敢", "过度依赖制度结构", "投资决策可能过于保守"],
    palace_effects_en: "In Life Palace: CFO type, reliable financial administrator. In Career Palace: banking, accounting, or government finance. In Wealth Palace: stable income through salaried positions.",
    palace_effects_zh: "在命宫：CFO类型，可靠的财务管理者。在官禄宫：银行、会计或政府财政。在财帛宫：通过薪资职位获得稳定收入。",
  },
  {
    slug: "tiantong-taiyin",
    star1_en: "Tian Tong (Heavenly Unity)",
    star1_zh: "天同",
    star2_en: "Tai Yin (Moon)",
    star2_zh: "太阴",
    nature_en: "Gentle Enjoyment + Feminine Grace",
    nature_zh: "温和享乐 + 阴柔优雅",
    description_en: "Tian Tong with Tai Yin creates the most gentle and aesthetically refined combination. These individuals have exceptional taste, emotional depth, and appreciation for beauty. They thrive in nurturing, artistic, or hospitality environments.",
    description_zh: "天同太阴同宫，创造了最温柔和审美精致的组合。这些人品味超群、情感深厚、欣赏美的能力强。在呵护型、艺术或服务环境中茁壮成长。",
    strengths_en: ["Exceptional aesthetic sense and taste", "Deeply empathetic and nurturing", "Creates harmonious environments", "Talent for arts, design, and hospitality"],
    strengths_zh: ["超群的审美感和品味", "深度共情且善于呵护", "创造和谐的环境", "艺术、设计和服务的天赋"],
    challenges_en: ["May lack ambition or competitive drive", "Overly sensitive to criticism", "Tendency toward passivity and procrastination"],
    challenges_zh: ["可能缺乏雄心或竞争动力", "对批评过度敏感", "倾向于被动和拖延"],
    palace_effects_en: "In Life Palace: artist, designer, or caring professional. In Spouse Palace: gentle, nurturing relationship. In Wealth Palace: income through beauty-related or service industries.",
    palace_effects_zh: "在命宫：艺术家、设计师或关怀型专业人士。在夫妻宫：温柔呵护的关系。在财帛宫：通过美容相关或服务业获利。",
  },
  {
    slug: "tiantong-jumen",
    star1_en: "Tian Tong (Heavenly Unity)",
    star1_zh: "天同",
    star2_en: "Ju Men (Giant Gate)",
    star2_zh: "巨门",
    nature_en: "Gentle Nature + Sharp Words",
    nature_zh: "温和本性 + 犀利言辞",
    description_en: "Tian Tong with Ju Men creates an interesting contrast — inner gentleness with outward verbal sharpness. These individuals may appear soft-spoken but possess incisive analytical and communication abilities. They often experience inner tension between harmony and truth-telling.",
    description_zh: "天同巨门同宫，创造了有趣的对比——内在温柔与外在言辞犀利。这些人看似柔和却有尖锐的分析和沟通能力。常在和谐与直言之间有内在张力。",
    strengths_en: ["Gentle delivery of sharp insights", "Non-threatening truth-teller", "Analytical mind with emotional awareness", "Effective communicator in sensitive situations"],
    strengths_zh: ["以温和方式传达犀利洞察", "不具威胁感的直言者", "兼有情感觉知的分析头脑", "敏感场合的有效沟通者"],
    challenges_en: ["Internal conflict between peace-seeking and truth-telling", "May suppress opinions to avoid conflict", "Others may underestimate their sharpness"],
    challenges_zh: ["求和与求真之间的内在冲突", "可能为避免冲突而压制观点", "他人可能低估其锐利"],
    palace_effects_en: "In Life Palace: counselor, therapist, or diplomatic critic. In Career Palace: success in HR, counseling, or gentle persuasion roles. In Health Palace: stress from suppressing communication.",
    palace_effects_zh: "在命宫：咨询师、治疗师或外交型评论家。在官禄宫：适合人事、心理咨询或温和说服的角色。在疾厄宫：压抑沟通带来的压力。",
  },
  {
    slug: "tiantong-tianliang",
    star1_en: "Tian Tong (Heavenly Unity)",
    star1_zh: "天同",
    star2_en: "Tian Liang (Heavenly Beam)",
    star2_zh: "天梁",
    nature_en: "Blessed Ease + Elder Protection",
    nature_zh: "福星 + 荫星庇护",
    description_en: "Tian Tong with Tian Liang doubles the blessing energy — the happiness star meets the protection star. These fortunate individuals often receive help at critical moments, encounter benefactors, and navigate through difficulties with surprising ease.",
    description_zh: "天同天梁同宫，福气加倍——福星遇上荫星。这些幸运者常在关键时刻获得帮助、遇到贵人，以惊人的轻松度过难关。",
    strengths_en: ["Naturally attracts helpers and benefactors", "Ability to turn crises into blessings", "Protected from severe misfortune", "Easygoing nature that disarms opponents"],
    strengths_zh: ["天然吸引贵人和帮助者", "化危为福的能力", "免于严重厄运的庇护", "化解对手的随和性情"],
    challenges_en: ["May become complacent due to easy rescues", "Lack of urgency can lead to underachievement", "Others may resent their apparent 'luck'"],
    challenges_zh: ["因容易获救而自满", "缺乏紧迫感导致发挥不足", "他人可能嫉妒其'好运'"],
    palace_effects_en: "In Life Palace: blessed life, things work out eventually. In Health Palace: recovery from illness is easier. In Parents Palace: strong family support system.",
    palace_effects_zh: "在命宫：有福之人，事情终会好转。在疾厄宫：疾病恢复较容易。在父母宫：强大的家庭支持系统。",
  },
  {
    slug: "lianzhen-tianfu",
    star1_en: "Lian Zhen (Purity)",
    star1_zh: "廉贞",
    star2_en: "Tian Fu (Treasury)",
    star2_zh: "天府",
    nature_en: "Ambitious Drive + Stable Foundation",
    nature_zh: "进取锋芒 + 稳固根基",
    description_en: "Lian Zhen with Tian Fu tempers the restless ambition of Lian Zhen with Tian Fu's stability. This produces driven individuals who channel their intensity into building lasting institutions rather than burning out in short bursts.",
    description_zh: "廉贞天府同宫，天府的稳重制约了廉贞的躁动野心。产生将强烈进取心导入建设持久事业的人，而非在短期爆发中燃尽。",
    strengths_en: ["Ambitious drive with strategic patience", "Builds lasting organizations", "Charismatic leadership with financial backing", "Channels intensity productively"],
    strengths_zh: ["有战略耐心的进取心", "建设持久的组织", "有财力支撑的魅力型领导", "将强烈能量导向生产力"],
    challenges_en: ["Internal tension between risk-taking and conservatism", "May appear unpredictable to others", "Desire for control can create power struggles"],
    challenges_zh: ["冒险与保守之间的内在张力", "他人可能觉得难以预测", "控制欲可能产生权力斗争"],
    palace_effects_en: "In Life Palace: institutional builder with edge. In Career Palace: corporate executive with entrepreneurial spirit. In Wealth Palace: significant wealth through strategic patience.",
    palace_effects_zh: "在命宫：有锋芒的制度建设者。在官禄宫：有创业精神的企业高管。在财帛宫：通过战略耐心获得可观财富。",
  },
  {
    slug: "lianzhen-tanlang",
    star1_en: "Lian Zhen (Purity)",
    star1_zh: "廉贞",
    star2_en: "Tan Lang (Greedy Wolf)",
    star2_zh: "贪狼",
    nature_en: "Passionate Intensity + Worldly Desire",
    nature_zh: "热烈锋芒 + 世俗欲望",
    description_en: "Lian Zhen with Tan Lang creates maximum intensity in desire and ambition — the secondary romance star meets the primary romance star. This produces passionate, magnetic individuals with strong appetites for life's pleasures and achievements.",
    description_zh: "廉贞贪狼同宫，欲望与野心达到最大强度——次桃花星遇上正桃花星。产生热情、有磁性的人，对生活的快乐和成就有强烈渴望。",
    strengths_en: ["Extremely magnetic and attractive personality", "Passionate pursuit of goals", "Versatile talents across many domains", "Natural entertainer and networker"],
    strengths_zh: ["极具磁性和吸引力的人格", "对目标的热烈追求", "跨领域的多才多艺", "天生的表演者和社交达人"],
    challenges_en: ["Strong romantic complications", "Addictive tendencies and excess", "May burn bridges through impulsive passion"],
    challenges_zh: ["强烈的感情纠纷", "上瘾倾向和过度行为", "可能因冲动的热情而断送关系"],
    palace_effects_en: "In Life Palace: magnetic personality, possible celebrity. In Spouse Palace: intense but turbulent romance. In Career Palace: entertainment, nightlife, or creative industries.",
    palace_effects_zh: "在命宫：磁性人格，可能成为名人。在夫妻宫：强烈但动荡的感情。在官禄宫：娱乐、夜生活或创意产业。",
  },
  {
    slug: "lianzhen-qisha",
    star1_en: "Lian Zhen (Purity)",
    star1_zh: "廉贞",
    star2_en: "Qi Sha (Seven Kills)",
    star2_zh: "七杀",
    nature_en: "Fierce Ambition + Warrior Courage",
    nature_zh: "刚烈进取 + 将帅之勇",
    description_en: "Lian Zhen with Qi Sha produces one of the most intense and driven combinations. Both stars carry martial energy, creating fearless competitors who stop at nothing to achieve their goals. They are natural warriors in business or military contexts.",
    description_zh: "廉贞七杀同宫产生最强烈和进取的组合之一。两颗星都携带武力能量，创造不达目的决不罢休的无畏竞争者。是商战或军事环境中的天生战士。",
    strengths_en: ["Unstoppable determination and willpower", "Fearless in the face of opposition", "Extreme competence under pressure", "Natural authority in dangerous situations"],
    strengths_zh: ["不可阻挡的决心和意志力", "面对对手无所畏惧", "高压下的极致能力", "在危险情况中的天然权威"],
    challenges_en: ["Can be ruthless and alienate allies", "Difficulty showing vulnerability", "May create enemies through aggressive competition"],
    challenges_zh: ["可能冷酷无情疏远盟友", "难以展现脆弱", "激烈竞争可能树敌"],
    palace_effects_en: "In Life Palace: warrior personality, military or extreme sports. In Career Palace: rapid rise through fierce competition. In Health Palace: watch for injuries and burnout.",
    palace_effects_zh: "在命宫：战士型人格，军事或极限运动。在官禄宫：通过激烈竞争快速晋升。在疾厄宫：注意伤病和过劳。",
  },
  {
    slug: "lianzhen-pojun",
    star1_en: "Lian Zhen (Purity)",
    star1_zh: "廉贞",
    star2_en: "Po Jun (Breaker)",
    star2_zh: "破军",
    nature_en: "Intense Drive + Total Disruption",
    nature_zh: "锋芒毕露 + 彻底颠覆",
    description_en: "Lian Zhen with Po Jun is maximum disruption — two of the most volatile stars together. This produces radical change-makers who cannot tolerate stagnation. Their lives are marked by dramatic transformations, for better or worse.",
    description_zh: "廉贞破军同宫是最大程度的颠覆——两颗最具波动性的星曜在一起。产生不能容忍停滞的激进变革者。其人生以戏剧性转变为标志，无论好坏。",
    strengths_en: ["Absolute fearlessness in making changes", "Creative destruction that leads to innovation", "Never trapped in unfulfilling situations", "Intense life experiences that build wisdom"],
    strengths_zh: ["做出改变时的绝对无畏", "导向创新的创造性破坏", "永远不会困在不满意的境况中", "积累智慧的强烈人生体验"],
    challenges_en: ["Extreme instability in all life areas", "Difficulty maintaining long-term relationships", "Self-destructive tendencies when frustrated"],
    challenges_zh: ["生活各方面的极端不稳定", "难以维持长期关系", "受挫时的自毁倾向"],
    palace_effects_en: "In Life Palace: revolutionary, extreme life changes. In Spouse Palace: multiple relationships or dramatic partner changes. In Career Palace: radical career pivots, cannot stay in one role.",
    palace_effects_zh: "在命宫：革命者，极端人生变化。在夫妻宫：多段关系或伴侣剧变。在官禄宫：激进的职业转型，无法长守一职。",
  },
  {
    slug: "lianzhen-tianxiang",
    star1_en: "Lian Zhen (Purity)",
    star1_zh: "廉贞",
    star2_en: "Tian Xiang (Seal)",
    star2_zh: "天相",
    nature_en: "Ambition + Institutional Grace",
    nature_zh: "锋芒 + 制度优雅",
    description_en: "Lian Zhen with Tian Xiang tempers sharp ambition with diplomatic polish. The result is a politically astute individual who advances through institutions with both drive and grace, understanding how to play the game while maintaining principles.",
    description_zh: "廉贞天相同宫，外交修养制约锋利的野心。结果是政治敏锐的人，以进取心和优雅在体制内晋升，懂得如何博弈同时维护原则。",
    strengths_en: ["Political savvy with principled ambition", "Advances in hierarchies without making enemies", "Diplomatic yet determined", "Effective in government and corporate politics"],
    strengths_zh: ["有原则野心的政治智慧", "在等级体系中晋升而不树敌", "有外交手腕且坚定", "在政府和企业政治中有效"],
    challenges_en: ["May become overly calculating", "Tension between personal ambition and institutional loyalty", "Risk of becoming a political operator rather than a leader"],
    challenges_zh: ["可能变得过于精于算计", "个人野心与组织忠诚之间的张力", "有成为政客而非领袖的风险"],
    palace_effects_en: "In Life Palace: political talent, effective bureaucrat. In Career Palace: success in government or corporate hierarchies. In Friends Palace: strategic alliances.",
    palace_effects_zh: "在命宫：政治人才，高效的官员。在官禄宫：在政府或企业等级体系中成功。在仆役宫：战略性的联盟关系。",
  },
];

export function getAllCombinations(): ZiweiCombination[] {
  return ZIWEI_COMBINATIONS;
}

export function getCombinationBySlug(slug: string): ZiweiCombination | undefined {
  return ZIWEI_COMBINATIONS.find((c) => c.slug === slug);
}
