// Zi Wei Dou Shu — Classical Patterns (格局百科)

export interface ZiweiPattern {
  slug: string;
  name_en: string;
  name_zh: string;
  category: "superior" | "middle" | "support" | "malefic" | "basic";
  description_en: string;
  description_zh: string;
  conditions_en: string;
  conditions_zh: string;
  effects_en: string;
  effects_zh: string;
  famous_examples_en: string;
  famous_examples_zh: string;
}

export const ZIWEI_PATTERNS: ZiweiPattern[] = [
  // ===== SUPERIOR PATTERNS (上格) =====
  {
    slug: "zi-fu-chao-yuan",
    name_en: "Zi Fu Chao Yuan (Purple-Treasury Facing Origin)",
    name_zh: "紫府朝元",
    category: "superior",
    description_en: "One of the most auspicious patterns in Zi Wei Dou Shu. When Zi Wei and Tian Fu face the Life Palace from the Travel and Career palaces, it creates a configuration of supreme authority meeting steady wealth, blessing the native with both leadership and financial fortune.",
    description_zh: "紫微斗数中最吉利的格局之一。紫微和天府从迁移宫和官禄宫朝向命宫，形成至尊权威会合稳健财富的格局，赋予命主领导力和财运双重福报。",
    conditions_en: "Zi Wei and Tian Fu in the Three Harmonies palaces facing the Life Palace (specifically in Si-You-Chou or Yin-Wu-Xu framework). No major malefic stars disrupting.",
    conditions_zh: "紫微与天府分居三方朝向命宫（具体在巳酉丑或寅午戌的三合格局中）。无主要煞星破坏。",
    effects_en: "High social status, natural authority, wealth accumulation through leadership positions. Often indicates government officials, corporate executives, or respected community leaders. Financial stability throughout life.",
    effects_zh: "社会地位高，天生具权威感，通过领导职位积累财富。常见于政府官员、企业高管或受尊敬的社区领袖。一生财务稳定。",
    famous_examples_en: "Historically associated with imperial ministers and wealthy merchants who maintained both power and integrity.",
    famous_examples_zh: "历史上常与朝廷重臣和富商相关联，这些人既有权势又能保持清廉。",
  },
  {
    slug: "ri-yue-bing-ming",
    name_en: "Ri Yue Bing Ming (Sun-Moon Jointly Bright)",
    name_zh: "日月并明",
    category: "superior",
    description_en: "When the Sun (Tai Yang) and Moon (Tai Yin) are both in their bright positions — Sun in daytime palaces and Moon in nighttime palaces — this creates a harmonious balance of yin and yang energies illuminating the chart.",
    description_zh: "太阳和太阴各自处于明亮位置——太阳在日生宫位、太阴在夜生宫位——形成阴阳和谐照耀命盘的格局。",
    conditions_en: "Tai Yang in Si/Wu/Wei (daytime bright positions) and Tai Yin in Hai/Zi/Chou (nighttime bright positions), both forming favorable aspects to the Life Palace.",
    conditions_zh: "太阳在巳午未（日间明亮宫位）且太阴在亥子丑（夜间明亮宫位），二者均与命宫形成有利相位。",
    effects_en: "Balanced personality admired by all, success in both public career and private life. Strong reputation, generous nature, harmonious family. Often wealthy with good health.",
    effects_zh: "性格平衡受人敬仰，公开事业与私人生活双丰收。声誉好，性格慷慨，家庭和睦。常富裕且健康。",
    famous_examples_en: "Associated with balanced leaders who excel in both governance and cultural patronage, such as enlightened emperors and philanthropists.",
    famous_examples_zh: "与在治国和文化赞助方面都出色的平衡型领袖相关联，如开明的帝王和慈善家。",
  },
  {
    slug: "ji-yue-tong-liang",
    name_en: "Ji Yue Tong Liang (Secret-Moon-Same-Beam)",
    name_zh: "机月同梁",
    category: "superior",
    description_en: "When Tian Ji, Tai Yin, Tian Tong, and Tian Liang form a connected pattern in the chart, it creates a configuration emphasizing wisdom, service, and institutional success. These four gentle stars combine intellectual sharpness with nurturing qualities.",
    description_zh: "天机、太阴、天同、天梁在命盘中形成连接格局，强调智慧、服务和体制内成功。四颗温和星曜结合了智识锐利与温暖品质。",
    conditions_en: "Tian Ji, Tai Yin, Tian Tong, and Tian Liang occupying the Life Palace and its Three Harmonies palaces. Best formed in Yin-Wu-Xu or Shen-Zi-Chen frameworks.",
    conditions_zh: "天机、太阴、天同、天梁分布在命宫及其三方宫位。最佳形成于寅午戌或申子辰的框架中。",
    effects_en: "Success in government, academia, large organizations. Strong analytical ability paired with emotional intelligence. Career advancement through institutional channels. Good at advisory and planning roles.",
    effects_zh: "在政府、学术界、大型机构中成功。分析能力强且情商高。通过体制内渠道晋升。擅长顾问和规划角色。",
    famous_examples_en: "Classic pattern for successful civil servants, university professors, and organizational strategists.",
    famous_examples_zh: "经典的公务员、大学教授和组织战略家格局。",
  },
  {
    slug: "ming-zhu-chao-yuan",
    name_en: "Ming Zhu Chao Yuan (Bright Pearl Facing Origin)",
    name_zh: "明珠出海",
    category: "superior",
    description_en: "A rare and precious pattern where key stars align to 'present the pearl' — symbolizing hidden talent that eventually shines brilliantly. The native may face early obscurity but achieves great recognition later in life.",
    description_zh: "珍贵稀有的格局，关键星曜排列如'明珠出海'——象征隐藏的才华终将璀璨绽放。命主可能早年默默无闻，但晚年获得巨大认可。",
    conditions_en: "Tai Yang and Tai Yin in favorable positions with Tian Ji in the Life Palace or Three Harmonies, forming a configuration where intellectual light breaks through obstacles.",
    conditions_zh: "太阳和太阴处于有利位置，天机在命宫或三方，形成智识之光突破障碍的格局。",
    effects_en: "Late bloomer who achieves extraordinary success. Strong intellectual and creative gifts that require time to develop. Often associated with scholars, artists, and innovators who gain fame after middle age.",
    effects_zh: "大器晚成型，最终取得非凡成就。需要时间发展的强大智识和创造天赋。常与中年后成名的学者、艺术家和创新者相关。",
    famous_examples_en: "Associated with late-blooming scholars and artists whose works gained recognition posthumously or in later life.",
    famous_examples_zh: "与大器晚成的学者和艺术家相关联，其作品在晚年或身后获得认可。",
  },
  {
    slug: "fu-xing-chao-yuan",
    name_en: "Fu Xing Chao Yuan (Fortune Stars Facing Origin)",
    name_zh: "府相朝元",
    category: "superior",
    description_en: "Tian Fu and Tian Xiang facing the Life Palace from favorable angles creates a pattern of steady wealth meeting diplomatic grace. This indicates stable, respectable success built on trust and institutional competence.",
    description_zh: "天府和天相从有利角度朝向命宫，形成稳健财富会合外交风度的格局。意味着建立在信任和制度能力上的稳定、体面的成功。",
    conditions_en: "Tian Fu and Tian Xiang in the Three Harmonies palaces forming favorable aspects to the Life Palace. Enhanced when supported by auspicious minor stars.",
    conditions_zh: "天府和天相在三方宫位与命宫形成有利相位。有吉利辅星支持时更佳。",
    effects_en: "Trustworthy leadership, institutional success, steady wealth building. Career in finance, government, or established corporations. Reliable reputation that opens doors. Protected from major financial disasters.",
    effects_zh: "值得信赖的领导力，体制内成功，稳健积累财富。在金融、政府或大型企业的事业。可靠声誉为其开路。免受重大财务灾难。",
    famous_examples_en: "Pattern seen in long-serving ministers, trusted bank presidents, and family patriarchs who build lasting legacies.",
    famous_examples_zh: "常见于长期任职的大臣、受信赖的银行行长和建立持久家业的家族族长。",
  },
  {
    slug: "jun-chen-qing-yi",
    name_en: "Jun Chen Qing Yi (Ruler-Minister Meeting)",
    name_zh: "君臣庆会",
    category: "superior",
    description_en: "The emperor star (Zi Wei) is well-supported by minister stars (Tian Fu, Tian Xiang, Zuo Fu, You Bi) creating a harmonious court. This indicates a leader surrounded by capable helpers who amplify their power.",
    description_zh: "帝星紫微得到臣星（天府、天相、左辅、右弼）良好辅佐，形成君臣和谐的朝堂格局。意味着领袖周围有能干的助手放大其力量。",
    conditions_en: "Zi Wei in the Life Palace with Zuo Fu and/or You Bi flanking, and Tian Fu or Tian Xiang in favorable Three Harmonies positions. The more minister stars present, the stronger the pattern.",
    conditions_zh: "紫微坐命宫有左辅和/或右弼夹持，天府或天相在有利的三方位置。臣星越多格局越强。",
    effects_en: "Supreme leadership potential with loyal support network. Success comes through inspiring and delegating effectively. Natural ability to build high-performing teams. Often reaches the highest positions in their field.",
    effects_zh: "至高的领导潜力配以忠实的支持网络。通过有效激励和授权获得成功。天生的建立高效团队能力。常达到所在领域的最高位置。",
    famous_examples_en: "Historically linked to founding emperors and modern CEOs who built powerful organizations through excellent team selection.",
    famous_examples_zh: "历史上与开国皇帝和通过优秀团队选拔建立强大组织的现代CEO相关联。",
  },
  {
    slug: "zi-wei-zai-wu",
    name_en: "Zi Wei Zai Wu (Zi Wei at Noon)",
    name_zh: "紫微在午",
    category: "superior",
    description_en: "Zi Wei sitting in the Wu (Noon) palace position is considered extremely powerful — the emperor at the zenith. This represents maximum authority and visibility, like the sun at its highest point.",
    description_zh: "紫微坐午宫被认为极其强大——帝星居于天顶。代表最大的权威和能见度，如太阳在最高点。",
    conditions_en: "Zi Wei star located in the Wu (午) Earthly Branch position, ideally as the Life Palace star. Enhanced by the absence of major malefic stars and presence of auxiliary helpers.",
    conditions_zh: "紫微星位于午宫，理想情况是作为命宫主星。无主要煞星且有辅助吉星时更佳。",
    effects_en: "Commanding presence, natural authority recognized by all. Career success in leadership positions. Strong visibility and public recognition. Financial prosperity through power and status.",
    effects_zh: "气场强大，天然权威为众人所认。领导岗位上事业成功。能见度高，获得公众认可。通过权力和地位实现财务富裕。",
    famous_examples_en: "Pattern associated with rulers, generals, and modern-day executives who command rooms simply by presence.",
    famous_examples_zh: "与统治者、将军和当代仅凭气场就能掌控全场的高管相关联。",
  },
  {
    slug: "san-qi-jia-hui",
    name_en: "San Qi Jia Hui (Three Wonders Gathering)",
    name_zh: "三奇嘉会",
    category: "superior",
    description_en: "When the three transformation stars — Hua Lu (wealth), Hua Quan (power), and Hua Ke (fame) — all converge in the Life Palace or its Three Harmonies, it creates a rare triple blessing of money, authority, and reputation.",
    description_zh: "三个化星——化禄（财）、化权（权）、化科（名）——汇聚在命宫或其三方时，形成财权名三重福报的罕见格局。",
    conditions_en: "Hua Lu, Hua Quan, and Hua Ke appearing together in the Life Palace triangle (Life, Career, Wealth palaces). This is a birth-year-dependent pattern that occurs rarely.",
    conditions_zh: "化禄、化权、化科同时出现在命宫三角（命宫、官禄宫、财帛宫）。这是依赖出生年份的格局，出现概率较低。",
    effects_en: "Simultaneously blessed with wealth, power, and fame. Career trajectory that combines financial success with public recognition and real authority. Often indicates founding a successful enterprise or reaching peak positions.",
    effects_zh: "同时拥有财富、权力和名声。事业轨迹结合了财务成功、公众认可和实际权力。常意味着创办成功企业或达到巅峰职位。",
    famous_examples_en: "Rare pattern associated with tycoons, cultural icons, and leaders who achieve the trifecta of wealth, power, and lasting fame.",
    famous_examples_zh: "稀有格局，与商业巨头、文化偶像和同时获得财富、权力和持久名声的领袖相关联。",
  },
  {
    slug: "ri-li-zhong-tian",
    name_en: "Ri Li Zhong Tian (Sun Standing at Zenith)",
    name_zh: "日丽中天",
    category: "superior",
    description_en: "Tai Yang (Sun) in its brightest position — the Wu (Noon) palace — represents maximum solar brilliance. The sun at zenith illuminates everything, symbolizing a life of public service, generosity, and widespread influence.",
    description_zh: "太阳在最明亮的位置——午宫——代表最大的太阳光辉。日丽中天照耀一切，象征公共服务、慷慨和广泛影响力的一生。",
    conditions_en: "Tai Yang in the Wu (午) palace, especially as Life Palace or Career Palace star. Best when not afflicted by Hua Ji or major malefic stars.",
    conditions_zh: "太阳在午宫，尤其是作为命宫或官禄宫主星。不受化忌或主要煞星侵扰时最佳。",
    effects_en: "Brilliant public career, fame through service. Generous personality admired by many. Success in government, media, education, or any public-facing role. Strong father figure or male benefactor energy.",
    effects_zh: "辉煌的公众事业，通过服务获得名声。慷慨性格受人仰慕。在政府、传媒、教育或任何面向公众的角色中成功。强大的父亲形象或男性贵人能量。",
    famous_examples_en: "Associated with beloved public figures, philanthropists, and leaders known for generosity and warmth.",
    famous_examples_zh: "与受爱戴的公众人物、慈善家和以慷慨温暖著称的领袖相关联。",
  },
  {
    slug: "yue-lang-tian-men",
    name_en: "Yue Lang Tian Men (Moon Bright at Heaven's Gate)",
    name_zh: "月朗天门",
    category: "superior",
    description_en: "Tai Yin (Moon) in the Hai (亥) palace — its brightest nighttime position — creates a pattern of maximum lunar luminosity. This represents deep intuition, hidden wealth, and quiet but profound influence.",
    description_zh: "太阴在亥宫——其最明亮的夜间位置——形成最大月光辉度的格局。代表深层直觉、隐藏财富和安静但深远的影响力。",
    conditions_en: "Tai Yin in the Hai (亥) palace, ideally as Life Palace or Wealth Palace star. Enhanced when supported by Hua Lu or other wealth-enhancing stars.",
    conditions_zh: "太阴在亥宫，理想情况是作为命宫或财帛宫主星。有化禄或其他增财星支持时更佳。",
    effects_en: "Wealth through quiet accumulation, real estate, or feminine industries. Deep intuitive wisdom. Success that comes without aggressive pursuit. Strong connection to mother or female benefactors. Artistic and creative wealth.",
    effects_zh: "通过静默积累、房地产或女性产业获财。深层直觉智慧。不用激进追求也能成功。与母亲或女性贵人连接深厚。艺术和创意方面的财富。",
    famous_examples_en: "Associated with real estate magnates, intuitive investors, and cultural figures whose influence grows quietly over time.",
    famous_examples_zh: "与房地产巨头、直觉型投资者和影响力随时间静默增长的文化人物相关联。",
  },
  {
    slug: "wu-qu-chao-dou",
    name_en: "Wu Qu Chao Dou (Wu Qu Facing the Dipper)",
    name_zh: "武曲朝斗",
    category: "superior",
    description_en: "Wu Qu (Military Music) star in a powerful position facing Zi Wei (the Dipper/Emperor), creating a pattern of financial warrior serving the throne. This indicates exceptional wealth-generating ability combined with discipline and strategic thinking.",
    description_zh: "武曲星在强力位置朝向紫微（北斗帝星），形成财将效忠帝座的格局。意味着卓越的赚钱能力结合纪律和战略思维。",
    conditions_en: "Wu Qu in a strong palace position with Zi Wei in the facing or Three Harmonies position. Enhanced by Hua Lu or Tian Fu support.",
    conditions_zh: "武曲在强力宫位，紫微在对宫或三方位置。有化禄或天府支持时更强。",
    effects_en: "Exceptional financial talent, wealth through disciplined effort. Success in banking, finance, military, or technical fields. Self-made wealth through determination and skill. Often indicates millionaire potential.",
    effects_zh: "卓越的理财天赋，通过纪律性努力获财。在银行、金融、军事或技术领域成功。凭决心和技能白手起家。常意味着百万富翁的潜力。",
    famous_examples_en: "Pattern of self-made financiers, disciplined investors, and military leaders who parlayed service into wealth.",
    famous_examples_zh: "白手起家的金融家、自律的投资者和将服务转化为财富的军事领袖的格局。",
  },
  {
    slug: "lian-zhen-qing-bai",
    name_en: "Lian Zhen Qing Bai (Lian Zhen Pure & Clear)",
    name_zh: "廉贞清白",
    category: "superior",
    description_en: "Lian Zhen in a favorable position without malefic contamination exhibits its highest nature — principled ambition, political skill used for good, and success through integrity rather than manipulation.",
    description_zh: "廉贞在有利位置且无煞星污染时展现最高品性——有原则的野心，用于正道的政治技巧，通过正直而非操纵获得成功。",
    conditions_en: "Lian Zhen in the Life Palace or Career Palace without Fire Star, Bell Star, Yang Ren, or Tuo Luo. Ideally supported by Tian Xiang or Tian Fu.",
    conditions_zh: "廉贞在命宫或官禄宫，无火星、铃星、擎羊、陀罗。最好有天相或天府辅佐。",
    effects_en: "Success in politics, law, or corporate leadership through principled action. Known for integrity and fairness. Achieves power without moral compromise. Often rises to positions of judicial or regulatory authority.",
    effects_zh: "通过有原则的行动在政治、法律或企业领导层成功。以正直公正著称。不做道德妥协也能获得权力。常升至司法或监管权威职位。",
    famous_examples_en: "Associated with incorruptible judges, ethical politicians, and corporate leaders known for doing the right thing.",
    famous_examples_zh: "与清廉法官、有道德的政治家和以做正确事情著称的企业领导相关联。",
  },
  // ===== MIDDLE PATTERNS (中格) =====
  {
    slug: "yang-liang-chang-lu",
    name_en: "Yang Liang Chang Lu (Sun-Beam Prosperous Path)",
    name_zh: "阳梁昌禄",
    category: "middle",
    description_en: "Tai Yang and Tian Liang combined with Wen Chang and Lu Cun creates a pattern of intellectual brightness protected by wisdom. This combination favors scholarly achievement and government service.",
    description_zh: "太阳和天梁配合文昌和禄存，形成智慧光明受保护的格局。此组合有利于学术成就和仕途。",
    conditions_en: "Tai Yang and Tian Liang in favorable positions with Wen Chang and/or Lu Cun in the same palace or Three Harmonies. Best in Mao or Chen positions.",
    conditions_zh: "太阳和天梁在有利位置，文昌和/或禄存在同宫或三方。在卯或辰位最佳。",
    effects_en: "Academic excellence, success in civil examinations (modern: professional certifications), government career with good reputation. Known for wisdom and integrity. Teaching and mentoring abilities.",
    effects_zh: "学业优秀，科举（现代：专业资格考试）成功，仕途中有好声誉。以智慧和正直著称。有教学和指导能力。",
    famous_examples_en: "Traditional pattern for passing imperial examinations. Modern equivalent: top university graduates who enter prestigious careers.",
    famous_examples_zh: "传统的科举中第格局。现代等价：考入名校并进入显赫事业的人。",
  },
  {
    slug: "ji-liang-shan-tan",
    name_en: "Ji Liang Shan Tan (Secret-Beam Lecture Hall)",
    name_zh: "机梁善谈",
    category: "middle",
    description_en: "Tian Ji and Tian Liang together create a pattern emphasizing wisdom in speech and advisory capability. These are the chart's great counselors — people whose words carry weight and whose advice transforms situations.",
    description_zh: "天机和天梁同在形成强调言辞智慧和咨询能力的格局。这是命盘中的大谋士——其话语有分量、建议能改变局面的人。",
    conditions_en: "Tian Ji and Tian Liang together in the Life Palace or Career Palace. Enhanced by Wen Chang, Wen Qu, or Hua Ke.",
    conditions_zh: "天机和天梁同在命宫或官禄宫。有文昌、文曲或化科加持更佳。",
    effects_en: "Success as advisor, consultant, therapist, or spiritual teacher. Wisdom that people seek out. Ability to articulate complex truths simply. Career in counseling, coaching, traditional Chinese medicine, or religious/spiritual leadership.",
    effects_zh: "作为顾问、咨询师、治疗师或灵性导师成功。人们寻求的智慧。将复杂真理简单表达的能力。在咨询、教练、中医或宗教/灵性领导的事业。",
    famous_examples_en: "Pattern of wise elders, revered teachers, and counselors whose single piece of advice changes people's life trajectories.",
    famous_examples_zh: "智慧长者、受尊敬的老师和一句建议就能改变人生轨迹的咨询师的格局。",
  },
  {
    slug: "tan-huo-tong-gong",
    name_en: "Tan Huo Tong Gong (Greedy Wolf with Fire)",
    name_zh: "贪火同宫",
    category: "middle",
    description_en: "Tan Lang (Greedy Wolf) with Fire Star (Huo Xing) creates an explosive pattern of sudden fortune. The greedy wolf's desire meets fire's urgency, producing rapid and dramatic wealth acquisition — often through unexpected windfalls.",
    description_zh: "贪狼与火星同宫，形成暴发格局。贪狼的欲望遇上火星的急躁，产生快速而戏剧性的财富获取——常通过意外横财。",
    conditions_en: "Tan Lang and Huo Xing (Fire Star) in the same palace, ideally the Life Palace or Wealth Palace. The pattern is strongest in Yin and Wu positions.",
    conditions_zh: "贪狼和火星在同一宫位，理想的是命宫或财帛宫。在寅和午位最强。",
    effects_en: "Sudden wealth, unexpected windfalls, explosive career success. May come through speculation, entertainment, or unconventional paths. Fast rise but requires wisdom to maintain. Best in middle age rather than youth.",
    effects_zh: "暴富、意外横财、爆发性事业成功。可能通过投机、娱乐或非常规途径获得。快速崛起但需要智慧来维持。中年比青年时期更佳。",
    famous_examples_en: "Associated with lottery winners, entertainment industry sudden stars, and entrepreneurs who hit explosive growth.",
    famous_examples_zh: "与彩票中奖者、娱乐圈一夜成名者和企业爆发式增长的创业者相关联。",
  },
  {
    slug: "tan-ling-chao-yuan",
    name_en: "Tan Ling Chao Yuan (Wolf-Bell Facing Origin)",
    name_zh: "贪铃朝元",
    category: "middle",
    description_en: "Similar to the Fire-Wolf pattern but with Bell Star (Ling Xing) instead. Tan Lang with Ling Xing creates a delayed but equally powerful explosive fortune pattern. The bell's energy is slower to ignite but burns longer.",
    description_zh: "类似火贪格但以铃星替代。贪狼与铃星形成延迟但同样强大的暴发格局。铃星的能量点燃较慢但燃烧更持久。",
    conditions_en: "Tan Lang and Ling Xing (Bell Star) together, with favorable positions in the Life Palace triangle. Most effective in specific Earthly Branch positions.",
    conditions_zh: "贪狼和铃星同在，位于命宫三角的有利位置。在特定地支宫位最有效。",
    effects_en: "Delayed but lasting wealth explosion. Unlike the fire pattern which is sudden, the bell pattern builds gradually then erupts. Success in mature age. Wealth that comes through patience and accumulated effort.",
    effects_zh: "延迟但持久的财富爆发。不像火贪格那样突然，铃贪格是渐进积累后爆发。在成熟年龄成功。通过耐心和累积努力获得的财富。",
    famous_examples_en: "Pattern of patient entrepreneurs whose decades of work suddenly pay off spectacularly in middle or later age.",
    famous_examples_zh: "耐心创业者的格局，几十年的努力在中年或晚年突然获得惊人回报。",
  },
  {
    slug: "sha-po-lang",
    name_en: "Sha Po Lang (Kill-Break-Wolf)",
    name_zh: "杀破狼",
    category: "middle",
    description_en: "When Qi Sha (Seven Kills), Po Jun (Breaker), and Tan Lang (Greedy Wolf) form a connected triangle in the chart, it creates the most turbulent and transformative pattern. These three 'revolution stars' bring dramatic life changes.",
    description_zh: "七杀、破军、贪狼在命盘中形成三方连接时，构成最动荡和变革性的格局。这三颗'革命星'带来戏剧性的人生变化。",
    conditions_en: "Qi Sha, Po Jun, and Tan Lang in the Life Palace and its opposite/Three Harmonies positions. This naturally occurs in specific chart frameworks.",
    conditions_zh: "七杀、破军、贪狼分布在命宫及其对宫/三方位置。这在特定命盘框架中自然出现。",
    effects_en: "Life of dramatic transformation — multiple career changes, geographic relocations, relationship upheavals. Great potential for spectacular success OR dramatic failure. Entrepreneurial energy. Best suited for pioneering, adventurous lifestyles.",
    effects_zh: "戏剧性变革的人生——多次职业转换、地理迁移、关系变动。巨大的辉煌成功或戏剧性失败的潜力。创业能量。最适合开拓性、冒险型的生活方式。",
    famous_examples_en: "Common pattern among serial entrepreneurs, adventurers, military leaders who survived multiple battles, and self-reinventing artists.",
    famous_examples_zh: "常见于连续创业者、冒险家、经历多次战役的军事领袖和不断自我重塑的艺术家。",
  },
  {
    slug: "fu-bi-jia-zhu",
    name_en: "Fu Bi Jia Zhu (Left-Right Flanking the Lord)",
    name_zh: "辅弼夹主",
    category: "middle",
    description_en: "Zuo Fu (Left Assistant) and You Bi (Right Assistant) flanking the Life Palace lord creates a pattern of constant support. The native always finds helpers appearing at crucial moments, like having guardian angels on both sides.",
    description_zh: "左辅和右弼夹持命宫主星，形成持续有助力的格局。命主总在关键时刻出现帮助者，如两侧各有一位守护天使。",
    conditions_en: "Zuo Fu and You Bi in the palaces adjacent to the Life Palace (flanking position), or both in the Life Palace with the main star.",
    conditions_zh: "左辅和右弼在命宫相邻宫位（夹持位置），或二者同在命宫与主星同宫。",
    effects_en: "Natural ability to attract helpers and supporters. Never alone in challenges — assistance always appears. Good at teamwork and delegation. Career advancement through mentors and allies rather than solo effort.",
    effects_zh: "天然吸引帮助者和支持者的能力。挑战中从不孤单——总有援助出现。善于团队合作和授权。通过导师和盟友而非单打独斗实现事业晋升。",
    famous_examples_en: "Pattern of leaders who succeed through coalition-building rather than individual brilliance — prime ministers, party leaders, and collaborative CEOs.",
    famous_examples_zh: "通过联盟建设而非个人才华成功的领袖格局——首相、政党领袖和协作型CEO。",
  },
  {
    slug: "chang-qu-jia-ming",
    name_en: "Chang Qu Jia Ming (Literary Stars Flanking Life)",
    name_zh: "昌曲夹命",
    category: "middle",
    description_en: "Wen Chang and Wen Qu flanking the Life Palace bestows literary talent and academic fortune. The native is blessed with eloquence, writing ability, and success through intellectual pursuits.",
    description_zh: "文昌和文曲夹持命宫，赋予文学才华和学业运。命主拥有口才、写作能力，通过智识追求获得成功。",
    conditions_en: "Wen Chang and Wen Qu in palaces adjacent to the Life Palace, or both in the Three Harmonies forming a literary triangle.",
    conditions_zh: "文昌和文曲在命宫相邻宫位，或二者在三方形成文学三角。",
    effects_en: "Literary and academic talent, success through examinations, writing, or communication. Often indicates multiple degrees, published works, or media career. Elegant speech and refined artistic sensibility.",
    effects_zh: "文学和学术才华，通过考试、写作或传播获得成功。常意味着多个学位、出版作品或传媒事业。言辞优雅且有精致的艺术感受力。",
    famous_examples_en: "Classic pattern for scholars who pass examinations with top honors, celebrated authors, and media personalities known for eloquence.",
    famous_examples_zh: "经典的科举状元格局，著名作家和以口才闻名的传媒人物。",
  },
  // ===== SUPPORT PATTERNS (助力格) =====
  {
    slug: "lu-ma-jiao-chi",
    name_en: "Lu Ma Jiao Chi (Wealth-Horse Exchange)",
    name_zh: "禄马交驰",
    category: "support",
    description_en: "Lu Cun (Wealth Preserver) and Tian Ma (Celestial Horse) in exchanged or connected positions create a pattern of wealth through movement. Money comes through travel, trade, exports, or mobile businesses.",
    description_zh: "禄存和天马在交换或连接位置，形成通过运动获财的格局。财富来自旅行、贸易、出口或流动型生意。",
    conditions_en: "Lu Cun and Tian Ma in the same palace or in opposing/Three Harmonies positions to each other. Most powerful when connected to the Wealth or Career Palace.",
    conditions_zh: "禄存和天马在同宫或彼此对宫/三方位置。与财帛宫或官禄宫连接时最有力。",
    effects_en: "Wealth through mobility — international trade, logistics, travel industry, or overseas business. Money comes from being in motion rather than staying put. Often indicates foreign income or success abroad.",
    effects_zh: "通过流动获财——国际贸易、物流、旅游业或海外生意。财富来自流动而非固守。常意味着国外收入或海外成功。",
    famous_examples_en: "Pattern of successful traders, shipping magnates, and international business people who profit from movement of goods and people.",
    famous_examples_zh: "成功贸易商、航运巨头和从货物与人员流动中获利的国际商人的格局。",
  },
  {
    slug: "shuang-lu-jia-ming",
    name_en: "Shuang Lu Jia Ming (Double Wealth Flanking Life)",
    name_zh: "双禄夹命",
    category: "support",
    description_en: "Two wealth indicators (Lu Cun and Hua Lu) flanking or converging on the Life Palace create a double layer of financial protection. The native enjoys persistent wealth luck from multiple sources.",
    description_zh: "两个财富指标（禄存和化禄）夹持或汇聚于命宫，形成双层财务保护。命主享有来自多个来源的持续财运。",
    conditions_en: "Lu Cun and Hua Lu both aspecting or flanking the Life Palace. Can also manifest as both appearing in the Wealth Palace triangle.",
    conditions_zh: "禄存和化禄同时照拂或夹持命宫。也可表现为二者同时出现在财帛宫三角。",
    effects_en: "Strong financial luck throughout life, multiple income streams. Protected from poverty even in bad years. Natural affinity with money and material comfort. Often inherits AND creates wealth.",
    effects_zh: "一生财运强劲，多重收入来源。即使在不好的年份也免于贫困。与金钱和物质舒适有天然亲和力。常既继承又创造财富。",
    famous_examples_en: "Pattern of inheritors who also multiply their inheritance, and self-made people who always seem to land on their feet financially.",
    famous_examples_zh: "继承者同时将遗产翻倍的格局，以及在财务上总能化险为夷的白手起家者。",
  },
  {
    slug: "tian-yi-gui-ren",
    name_en: "Tian Yi Gui Ren (Heavenly Noble Helper)",
    name_zh: "天乙贵人",
    category: "support",
    description_en: "When the Heavenly Noble stars (Tian Kui and Tian Yue) are prominently placed, especially flanking the Life Palace, they create a persistent pattern of receiving help from powerful benefactors at critical moments.",
    description_zh: "天魁和天钺（天乙贵人星）位置显要，尤其是夹持命宫时，形成在关键时刻持续获得有力贵人帮助的格局。",
    conditions_en: "Tian Kui and Tian Yue in the Life Palace, flanking it, or prominently placed in the Career and Wealth palace triangle.",
    conditions_zh: "天魁和天钺在命宫、夹持命宫，或在官禄宫和财帛宫三角中位置显要。",
    effects_en: "Always receives help from noble people at crucial times. Mentors, sponsors, and benefactors appear throughout life. Often gets opportunities through introductions rather than cold applications. Career doors open through relationships.",
    effects_zh: "总在关键时刻获得贵人帮助。一生中不断出现导师、赞助者和恩人。常通过引荐而非自荐获得机会。事业之门通过人脉打开。",
    famous_examples_en: "Pattern seen in mentored proteges who rise quickly due to powerful sponsors — favored apprentices who become masters.",
    famous_examples_zh: "因强大赞助者而快速崛起的被栽培者格局——受青睐的学徒最终成为大师。",
  },
  {
    slug: "hua-lu-chao-yuan",
    name_en: "Hua Lu Chao Yuan (Transformation Wealth Facing Origin)",
    name_zh: "化禄朝元",
    category: "support",
    description_en: "When Hua Lu (Transformation of Wealth) appears in a key position facing the Life Palace, it indicates that one's birth year bestows a special wealth blessing. Resources flow naturally toward the native.",
    description_zh: "化禄出现在朝向命宫的关键位置时，意味着出生年份赋予了特殊的财富加持。资源自然流向命主。",
    conditions_en: "Hua Lu in the Career Palace, Wealth Palace, or Travel Palace facing the Life Palace. The star carrying Hua Lu determines the nature of wealth.",
    conditions_zh: "化禄在官禄宫、财帛宫或迁移宫朝向命宫。携带化禄的星曜决定了财富的性质。",
    effects_en: "Natural wealth magnetism in the area governed by the Hua Lu carrier star. Income comes with relative ease. Good financial intuition. Resources appear when needed for ventures.",
    effects_zh: "在化禄载体星所管领域具有天然聚财力。收入来得相对轻松。良好的财务直觉。创业所需资源在需要时出现。",
    famous_examples_en: "Common pattern among people who seem to effortlessly attract financial opportunities and whose investments tend to succeed.",
    famous_examples_zh: "常见于似乎毫不费力就能吸引财务机会、投资往往成功的人。",
  },
  {
    slug: "tian-ma-xing-kong",
    name_en: "Tian Ma Xing Kong (Celestial Horse Traveling)",
    name_zh: "天马行空",
    category: "support",
    description_en: "Tian Ma (Celestial Horse) in a powerful, unobstructed position creates a pattern of freedom, mobility, and success through travel. The native thrives when not confined to one place or routine.",
    description_zh: "天马在强力且无阻碍的位置，形成自由、流动和通过旅行成功的格局。命主在不被束缚于一处或一种模式时蓬勃发展。",
    conditions_en: "Tian Ma in the Life Palace or Travel Palace without being trapped by Kong Wang (Void) stars. Enhanced by Lu Cun or Hua Lu connection.",
    conditions_zh: "天马在命宫或迁移宫，不被空亡星困住。与禄存或化禄连接时增强。",
    effects_en: "Success through mobility and change. Career involving travel, relocation, or dynamic environments. Freedom-loving personality that performs best without restrictions. Often indicates expatriate success or nomadic wealth.",
    effects_zh: "通过流动和变化获得成功。涉及旅行、搬迁或动态环境的事业。热爱自由的性格在无限制时表现最佳。常意味着海外成功或游牧式的财富。",
    famous_examples_en: "Pattern of digital nomads, international consultants, traveling performers, and entrepreneurs with global operations.",
    famous_examples_zh: "数字游牧者、国际顾问、巡回演出者和全球经营的企业家的格局。",
  },
  {
    slug: "ke-ming-xing-gui",
    name_en: "Ke Ming Xing Gui (Fame Star Illuminating Noble)",
    name_zh: "科名星贵",
    category: "support",
    description_en: "Hua Ke (Transformation of Fame) with literary stars (Wen Chang/Wen Qu) creates a pattern of academic honor and public recognition through intellectual achievement. The native gains fame through knowledge and credentials.",
    description_zh: "化科与文星（文昌/文曲）配合，形成通过智识成就获得学术荣誉和公众认可的格局。命主通过知识和资历获得名声。",
    conditions_en: "Hua Ke in conjunction with Wen Chang or Wen Qu, aspecting the Life Palace or Career Palace. Enhanced by Tian Kui/Tian Yue presence.",
    conditions_zh: "化科与文昌或文曲同在，照拂命宫或官禄宫。有天魁/天钺时增强。",
    effects_en: "Academic honors, professional certifications, published recognition. Fame through expertise and credentials. Success in examinations, scholarship applications, and peer review. Respected authority in chosen field.",
    effects_zh: "学术荣誉、专业资格、出版认可。通过专业知识和资历获得名声。考试、奖学金申请和同行评审中成功。在所选领域中受尊敬的权威。",
    famous_examples_en: "Pattern of Nobel laureates, nationally recognized scholars, and professionals whose credentials open all doors.",
    famous_examples_zh: "诺贝尔奖获得者、全国知名学者和资历为其打开所有大门的专业人士的格局。",
  },
  // ===== MALEFIC PATTERNS (恶格) =====
  {
    slug: "ming-li-tao-hua",
    name_en: "Ming Li Tao Hua (Peach Blossom in Life Palace)",
    name_zh: "命里桃花",
    category: "malefic",
    description_en: "Excessive Peach Blossom (romantic) stars concentrated in the Life Palace create a pattern of emotional entanglement and relationship chaos. While charming, the native attracts too much romantic attention that disrupts life stability.",
    description_zh: "过多桃花星集中在命宫，形成感情纠缠和关系混乱的格局。虽然有魅力，但命主吸引过多浪漫关注，扰乱生活稳定。",
    conditions_en: "Multiple Peach Blossom indicators (Tan Lang, Tian Yao, Xian Chi, Hong Luan) concentrated in the Life Palace or Spouse Palace, especially when afflicted by Hua Ji.",
    conditions_zh: "多颗桃花指标星（贪狼、天姚、咸池、红鸾）集中在命宫或夫妻宫，尤其受化忌侵扰时。",
    effects_en: "Chronic relationship instability, attraction of inappropriate partners, scandal risk. Charm becomes a liability when it attracts obsessive attention. Energy drained by emotional drama rather than productive pursuits.",
    effects_zh: "慢性的关系不稳定，吸引不合适的伴侣，丑闻风险。当魅力吸引强迫性关注时成为负担。精力被情感纠葛而非生产性追求所消耗。",
    famous_examples_en: "Pattern associated with celebrities whose personal scandals overshadow their talents, and historical figures ruined by romantic entanglements.",
    famous_examples_zh: "与个人丑闻盖过才华的名人相关联，以及被感情纠葛毁掉的历史人物。",
  },
  {
    slug: "xing-nang-jia-ming",
    name_en: "Xing Nang Jia Ming (Punishment Stars Flanking Life)",
    name_zh: "刑囊夹命",
    category: "malefic",
    description_en: "When punishing stars (Yang Ren, Tuo Luo, or Tian Xing) flank the Life Palace, they create a pattern of conflict, litigation, and physical danger. The native faces repeated clashes with authority or law.",
    description_zh: "刑星（擎羊、陀罗或天刑）夹持命宫时，形成冲突、诉讼和人身危险的格局。命主反复与权威或法律冲突。",
    conditions_en: "Yang Ren and Tuo Luo flanking the Life Palace, or Tian Xing with other malefic stars creating a punishing triangle around the Life Palace.",
    conditions_zh: "擎羊和陀罗夹持命宫，或天刑与其他煞星围绕命宫形成刑罚三角。",
    effects_en: "Proneness to legal troubles, physical injuries, conflicts with authority. Risk of imprisonment or serious litigation. Aggressive temperament that creates enemies. Requires conscious effort to avoid confrontations.",
    effects_zh: "容易遇到法律麻烦、身体伤害、与权威冲突。有入狱或严重诉讼风险。激进性格制造仇敌。需要有意识地避免对抗。",
    famous_examples_en: "Pattern seen in historical figures who faced exile, imprisonment, or execution despite talent — those whose aggression led to their downfall.",
    famous_examples_zh: "见于尽管有才华仍遭流放、入狱或处决的历史人物——那些攻击性导致自身覆灭的人。",
  },
  {
    slug: "huo-ling-jia-ming",
    name_en: "Huo Ling Jia Ming (Fire-Bell Flanking Life)",
    name_zh: "火铃夹命",
    category: "malefic",
    description_en: "Fire Star and Bell Star flanking the Life Palace creates a pattern of explosive temper and sudden disasters. Life is punctuated by crises that arrive without warning, often through the native's own impulsiveness.",
    description_zh: "火星和铃星夹持命宫，形成爆发性脾气和突发灾难的格局。人生充满毫无预警到来的危机，常因命主自身的冲动所致。",
    conditions_en: "Huo Xing (Fire Star) and Ling Xing (Bell Star) in palaces adjacent to the Life Palace, creating a burning pressure on both sides.",
    conditions_zh: "火星和铃星在命宫两侧相邻宫位，形成双面灼烧压力。",
    effects_en: "Explosive temperament, sudden losses, accident-prone life. Career instability due to impulsive decisions. Relationship destruction through anger. However, can be channeled into martial arts, emergency services, or competitive sports.",
    effects_zh: "爆发性脾气、突然损失、事故频发的人生。因冲动决策导致事业不稳。因愤怒破坏关系。但可引导至武术、急救服务或竞技体育。",
    famous_examples_en: "Pattern of brilliant but self-destructive individuals — generals who won battles but lost through insubordination, or artists whose rage fueled both creation and destruction.",
    famous_examples_zh: "才华横溢但自我毁灭的人格局——赢得战役但因不服从而败亡的将军，或愤怒同时驱动创作和毁灭的艺术家。",
  },
  {
    slug: "ji-xing-chan-ming",
    name_en: "Ji Xing Chan Ming (Transformation Jealousy Wrapping Life)",
    name_zh: "忌星缠命",
    category: "malefic",
    description_en: "Multiple Hua Ji (Transformation of Jealousy/Obstruction) energies concentrated on the Life Palace create persistent blockages, frustration, and setbacks. Whatever the native attempts faces unusual resistance.",
    description_zh: "多重化忌能量集中在命宫，形成持续阻滞、挫折和挫败的格局。命主的一切尝试都遇到异常阻力。",
    conditions_en: "Birth year Hua Ji plus decade or annual Hua Ji both affecting the Life Palace. Worse when Hua Ji lands on an already weak star in the Life Palace.",
    conditions_zh: "出生年化忌加上大限或流年化忌同时影响命宫。化忌落在命宫中已经弱势的星曜上时更差。",
    effects_en: "Persistent obstacles, things that should work somehow don't. Mental stress and frustration. Relationships and career face repeated unexplained blockages. Requires extra effort for normal results. Best coped with through patience and spiritual practice.",
    effects_zh: "持续的障碍，应该顺利的事偏偏不顺。精神压力和挫败感。关系和事业面临反复的莫名阻碍。正常结果需要额外努力。最好通过耐心和灵性修行应对。",
    famous_examples_en: "Pattern of late-blooming geniuses who faced decades of rejection, and historical figures whose talents were only recognized posthumously.",
    famous_examples_zh: "面对数十年拒绝的大器晚成天才的格局，以及才华仅在身后获认可的历史人物。",
  },
  {
    slug: "kong-jie-jia-ming",
    name_en: "Kong Jie Jia Ming (Void Stars Flanking Life)",
    name_zh: "空劫夹命",
    category: "malefic",
    description_en: "Di Kong (Earth Void) and Di Jie (Earth Robbery) flanking the Life Palace create a pattern of material emptiness — wealth slips away, plans collapse, and material security feels perpetually elusive.",
    description_zh: "地空和地劫夹持命宫，形成物质空虚的格局——财富流失、计划崩塌，物质安全感总是难以捉摸。",
    conditions_en: "Di Kong and Di Jie in palaces adjacent to the Life Palace. Also problematic when both are in the Wealth Palace or Career Palace.",
    conditions_zh: "地空和地劫在命宫相邻宫位。二者同在财帛宫或官禄宫时同样有问题。",
    effects_en: "Financial instability, plans that never materialize, feeling of emptiness despite effort. However, this pattern can indicate spiritual gifts — the material void opens space for philosophical or artistic depth. Many monks and artists have this pattern.",
    effects_zh: "财务不稳定、计划永远无法实现、尽管努力仍感空虚。但此格局可能意味着灵性天赋——物质的空无为哲学或艺术深度打开空间。许多僧人和艺术家有此格局。",
    famous_examples_en: "Pattern of spiritual seekers, abstract artists, and philosophers who traded material wealth for profound inner understanding.",
    famous_examples_zh: "以物质财富换取深刻内在领悟的灵性追求者、抽象艺术家和哲学家的格局。",
  },
  {
    slug: "lian-sha-po-jun",
    name_en: "Lian Sha Po Jun (Integrity-Kill-Breaker)",
    name_zh: "廉杀破军",
    category: "malefic",
    description_en: "When Lian Zhen combines with Qi Sha or Po Jun in an afflicted position, it creates one of the most dangerous patterns — sharp ambition without restraint, leading to self-destructive behavior or criminal tendencies.",
    description_zh: "廉贞与七杀或破军在受侵位置结合，形成最危险的格局之一——锋利的野心失去约束，导致自我毁灭行为或犯罪倾向。",
    conditions_en: "Lian Zhen with Qi Sha or Po Jun, afflicted by Fire Star, Bell Star, Yang Ren, or Hua Ji. Especially dangerous in the Life Palace or Health Palace.",
    conditions_zh: "廉贞与七杀或破军同在，受火星、铃星、擎羊或化忌侵扰。在命宫或疾厄宫尤其危险。",
    effects_en: "Risk of criminal behavior, imprisonment, serious accidents, or self-destruction. Extreme competitiveness that crosses ethical lines. Potential for violence or being victimized by violence. Requires strong moral education and self-discipline to redirect.",
    effects_zh: "犯罪行为、入狱、严重事故或自我毁灭的风险。跨越道德底线的极端竞争性。暴力伤害或被暴力伤害的可能。需要强大的道德教育和自律来重新引导。",
    famous_examples_en: "Historical pattern associated with ambitious figures who fell from grace — corrupt officials, failed revolutionaries, and those destroyed by their own ruthlessness.",
    famous_examples_zh: "与雄心勃勃却失足落马的人物相关——贪官、失败的革命者和被自身无情所毁灭的人。",
  },
  // ===== BASIC PATTERNS (基础格局) =====
  {
    slug: "ming-wu-zheng-yao",
    name_en: "Ming Wu Zheng Yao (Life Palace Without Major Star)",
    name_zh: "命无正曜",
    category: "basic",
    description_en: "When the Life Palace contains no major (14 main) star, the chart interpretation relies heavily on the opposite palace stars and auxiliary stars. This is not inherently bad or good — it creates a more complex, environment-dependent personality.",
    description_zh: "命宫无十四主星时，命盘解读严重依赖对宫星曜和辅助星。这本身不好也不坏——创造出更复杂、依赖环境的性格。",
    conditions_en: "No 14 major stars physically present in the Life Palace. Interpretation shifts to the opposite palace (Travel Palace) stars which 'shine across' to influence the Life Palace.",
    conditions_zh: "命宫中无十四主星实际存在。解读转向对宫（迁移宫）星曜，它们'借照'影响命宫。",
    effects_en: "Highly adaptable personality that mirrors surroundings. Success depends heavily on environment and companions. More susceptible to external influences. Can be chameleon-like advantage in social/diplomatic careers, but may lack a strong core identity.",
    effects_zh: "高度适应性格，映射周围环境。成功严重依赖环境和同伴。更容易受外部影响。在社交/外交事业中可能是变色龙般的优势，但可能缺乏强大的核心认同。",
    famous_examples_en: "Pattern of diplomats, actors, and social chameleons who become whoever the situation requires — strength in adaptability.",
    famous_examples_zh: "外交官、演员和社会变色龙的格局——根据情境需要成为不同的人——在适应力中见优势。",
  },
  {
    slug: "ming-shen-tong-gong",
    name_en: "Ming Shen Tong Gong (Life-Body Same Palace)",
    name_zh: "命身同宫",
    category: "basic",
    description_en: "When the Life Palace and Body Palace overlap in the same position, it concentrates all of one's fundamental energies into a single focal point. This creates intense, focused individuals whose destiny and effort align in one direction.",
    description_zh: "命宫和身宫重叠在同一位置时，将所有基本能量集中到单一焦点。创造出密集、专注的人，命运和努力朝同一方向对齐。",
    conditions_en: "The calculated Life Palace and Body Palace fall in the same Earthly Branch position. This occurs in specific birth hour configurations.",
    conditions_zh: "计算出的命宫和身宫落在同一地支位置。这在特定出生时辰配置中出现。",
    effects_en: "Intense focus — what you want and what you do are perfectly aligned. No internal conflict between desire and duty. Strong life momentum in one direction. Can be extremely successful in their chosen path but may lack balance or flexibility.",
    effects_zh: "强烈的专注——想要的和做的完美对齐。欲望与责任之间无内在冲突。人生在一个方向上有强大动力。在选择的道路上可极其成功，但可能缺乏平衡或灵活性。",
    famous_examples_en: "Pattern of single-minded achievers — Olympic athletes, dedicated scientists, and monastic practitioners who pour everything into one pursuit.",
    famous_examples_zh: "一心一意的成就者格局——奥运运动员、专注的科学家和将一切投入单一追求的修行者。",
  },
  {
    slug: "ri-sheng-ye-sheng",
    name_en: "Ri Sheng / Ye Sheng (Day Birth / Night Birth)",
    name_zh: "日生夜生",
    category: "basic",
    description_en: "Whether one is born during day (卯-申 hours) or night (酉-寅 hours) fundamentally affects how Sun and Moon stars express their energy. Day births strengthen Tai Yang; night births strengthen Tai Yin.",
    description_zh: "出生在白天（卯至申时）还是夜晚（酉至寅时）从根本上影响太阳和太阴星的能量表达。日生强化太阳；夜生强化太阴。",
    conditions_en: "Day birth: born between Mao hour (5-7 AM) and Shen hour (3-5 PM). Night birth: born between You hour (5-7 PM) and Yin hour (3-5 AM).",
    conditions_zh: "日生：生于卯时（5-7点）至申时（15-17点）之间。夜生：生于酉时（17-19点）至寅时（3-5点）之间。",
    effects_en: "Day births: Sun's positive qualities enhanced — public success, generosity, visibility. Night births: Moon's positive qualities enhanced — intuition, wealth accumulation, inner wisdom. This basic condition modifies all other pattern interpretations.",
    effects_zh: "日生：太阳正面品质增强——公众成功、慷慨、能见度。夜生：太阴正面品质增强——直觉、聚财、内在智慧。此基本条件影响所有其他格局的解读。",
    famous_examples_en: "A fundamental modifier rather than a standalone pattern — it enhances or diminishes the effectiveness of Sun and Moon in any chart configuration.",
    famous_examples_zh: "基础修正因素而非独立格局——它增强或减弱太阳和太阴在任何命盘配置中的有效性。",
  },
  {
    slug: "wu-xing-ju",
    name_en: "Wu Xing Ju (Five Element Bureau)",
    name_zh: "五行局",
    category: "basic",
    description_en: "The Five Element Bureau (Water-2, Wood-3, Metal-4, Earth-5, Fire-6) determines the fundamental elemental nature of the chart and affects the timing of major star placements. It is the basic framework upon which all other patterns are built.",
    description_zh: "五行局（水二局、木三局、金四局、土五局、火六局）决定命盘的基本五行属性，影响主星安放的时间。是所有其他格局建立的基础框架。",
    conditions_en: "Determined by the combination of Life Palace Earthly Branch and birth year Heavenly Stem. Each person has exactly one Five Element Bureau that never changes.",
    conditions_zh: "由命宫地支和出生年天干的组合确定。每人有且仅有一个五行局，终生不变。",
    effects_en: "Water-2: early bloomer, flexible. Wood-3: growing steadily, creative. Metal-4: sharp, decisive, peaks in middle age. Earth-5: stable, late development. Fire-6: latest bloomer but most explosive when activated.",
    effects_zh: "水二局：早发，灵活。木三局：稳步成长，有创造力。金四局：锐利果断，中年巅峰。土五局：稳定，大器晚成。火六局：最晚发但激活后最具爆发力。",
    famous_examples_en: "Not a standalone fortune pattern — it's the fundamental timing mechanism that determines when life peaks occur and how other patterns manifest.",
    famous_examples_zh: "非独立的运势格局——是决定人生高峰何时出现以及其他格局如何显现的基本计时机制。",
  },
  {
    slug: "si-hua-fei-xing",
    name_en: "Si Hua Fei Xing (Four Transformations Flying Stars)",
    name_zh: "四化飞星",
    category: "basic",
    description_en: "The Four Transformations (Hua Lu, Hua Quan, Hua Ke, Hua Ji) assigned by birth year create the dynamic layer of the chart. They transform static star placements into active energies, creating the unique 'destiny signature' of each chart.",
    description_zh: "由出生年份分配的四化（化禄、化权、化科、化忌）创造命盘的动态层。将静态星曜配置转化为活跃能量，形成每张命盘独特的'命运签名'。",
    conditions_en: "Each birth year assigns four transformations to specific stars. These are fixed at birth and modify the inherent nature of those stars permanently in the natal chart.",
    conditions_zh: "每个出生年份将四化分配给特定星曜。这些在出生时固定，永久修改那些星曜在本命盘中的固有性质。",
    effects_en: "Hua Lu: adds wealth/smoothness. Hua Quan: adds power/determination. Hua Ke: adds fame/recognition. Hua Ji: adds obstruction/lessons. Together they create the unique challenge-and-gift profile of each individual.",
    effects_zh: "化禄：增加财富/顺遂。化权：增加权力/决断。化科：增加名声/认可。化忌：增加阻碍/课题。合在一起构成每个人独特的挑战与天赋组合。",
    famous_examples_en: "The foundation of Flying Star Zi Wei Dou Shu school — understanding these transformations is key to advanced chart reading and prediction.",
    famous_examples_zh: "飞星紫微斗数流派的基础——理解这些变化是高级命盘解读和预测的关键。",
  },
];

export function getAllPatterns(): ZiweiPattern[] {
  return ZIWEI_PATTERNS;
}

export function getPatternBySlug(slug: string): ZiweiPattern | undefined {
  return ZIWEI_PATTERNS.find((p) => p.slug === slug);
}

export function getPatternsByCategory(category: ZiweiPattern["category"]): ZiweiPattern[] {
  return ZIWEI_PATTERNS.filter((p) => p.category === category);
}
